apiVersion: v1
kind: Service
metadata:
  name: horror-game-frontend
  namespace: horror-game
  labels:
    app: horror-game
    component: frontend
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: horror-game
    component: frontend 