apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: horror-game
  labels:
    app: horror-game
    component: redis
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
      name: redis
  selector:
    app: horror-game
    component: redis 